// "use server"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
  export default function Layout({ children, }: {children: React.ReactNode}) {
    return (
      
        <main >
          <nav className=''>
            <h1>This is on layout</h1>
          </nav>
          {children}
        </main>
      
    )
  }
  