// "use server"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <main >
        <nav className=''>
          <h1>About</h1>
        </nav>
        {children}
      </main>
    
  )
}
